# Generated by Django 2.1.7 on 2019-04-09 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diafo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('questionnaire', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='diafo.Questionnaire')),
            ],
        ),
    ]
