# Generated by Django 2.2 on 2019-04-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='batch',
            field=models.CharField(default='all', max_length=100),
        ),
    ]
