# Generated by Django 2.2 on 2019-04-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20190410_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='phase',
            field=models.CharField(choices=[('IP', 'Initial Phase'), ('NP', 'Nomination Phase'), ('CP', 'Campaign Phase'), ('PP', 'Polling Phase'), ('OPP', 'Offline Polling Phase'), ('MP', 'Mid Phase'), ('RP', 'Result Phase'), ('EP', 'End Phase')], default='IP', max_length=30),
        ),
    ]
