# Generated by Django 2.2 on 2019-04-18 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diafo.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='form',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
