# Generated by Django 2.2 on 2019-04-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='program',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='roll_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='room_no',
            field=models.IntegerField(default=0),
        ),
    ]
