# Generated by Django 2.1.7 on 2019-04-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='block',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='program',
            field=models.CharField(default='', max_length=10),
        ),
    ]
