# Generated by Django 2.1.7 on 2019-04-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190410_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='block',
        ),
    ]
